
export const games = [
    // {
    //     name: "ROAR Picture Vocabulary",
    //     id: "vocab",
    //     startBtn: ".jspsych-btn",
    //     introBtn: ".continue",
    //     introIters: 3,
    //     setUpChoice: ".intro_aliens",
    //     clickableItem: ".vocab_img",
    //     numIter: 4,
    // },
    // {
    //     name: "ROAR Written Vocabulary",
    //     id: "cva",
    //     startBtn: ".jspsych-fullscreen-btn",
    //     introBtn: ".go-button",
    //     introIters: 2,
    //     setupChoice: "",
    //     clickableItem: "button",
    //     numIter: 4,
    // },
    // {
    //     name: "Letter",
    //     id: "letter",
    //     startBtn: ".jspsych-fullscreen-btn",
    //     introBtn: ".go-button",
    //     introIters: 5,
    //     correctChoice: ".glowingButton",
    //     setupChoice: "",
    //     clickableItem: "button",
    //     //somewhere between 20 and 40... hahah should do this smarter
    //     numIter: 28,
    // },
    // {
    //     name: "ROAR-Morphology",
    //     id: "multichoice",
    //     startBtn: ".jspsych-fullscreen-btn",
    //     introBtn: ".go-button",
    //     introIters: 3 ,
    //     clickableItem: "button",
    //     setupChoice: "",
    //     correctChoice: ".glowingButton",
    //     numIter: 4,
    // },
    // // pa has a different start button than the others (.continue i think)
    {
        name: "ROAR-Phoneme",
        id: "pa",
        startBtn: ".instructionCanvasNS",
        startBtn2: ".jspsych-btn",
        setUpChoice: "",
        introIters: 2,
        introBtn: ".continue",
        clickableItem: ".jspsych-audio-button-response-button",
        correctChoice: "",
        numIter: 2,
    },
    // sre isnt working?
    // {
    //     name: "ROAR-Sentence",
    //     id: "sre",
    //     startBtn: ".jspsych-fullscreen-btn",
    //     introBtn: ".go-button",
    //     introIters: 3,
    //     setUpChoice: "",
    //     clickableItem: "button",
    //     correctChoice: "",
    //     numIter: 4,
    // },
    // swr isnt working?
    // {
    //     name: "ROAR-Word",
    //     id: "swr",
    //     startBtn: ".jspsych-fullscreen-btn",
    //     introBtn: ".go-button",
    //     introIters: 3,
    //     setUpChoice: "",
    //     clickableItem: "button",
    //     correctChoice: "",
    //     numIter: 4,
    // },
]


