
export const games = [
    // {
    //     name: "ROAR Picture Vocabulary",
    //     id: "vocab",
    //     startBtn: ".jspsych-btn",
    //     introBtn: ".continue",
    //     introIters: 3,
    //     setUpChoice: ".intro_aliens",
    //     clickableItem: ".vocab_img",
    //     numIter: 4,
    // },
    // {
    //     name: "ROAR Written Vocabulary",
    //     id: "cva",
    //     startBtn: ".jspsych-fullscreen-btn",
    //     introBtn: ".go-button",
    //     introIters: 2,
    //     setupChoice: "",
    //     clickableItem: "button",
    //     numIter: 4,
    // },
    // letter is a little tricky -- it requires the selection of the correct choice (there are two of these intro questions)
    // {
    //     name: "Letter",
    //     id: "letter",
    //     startBtn: ".jspsych-fullscreen-btn",
    //     introBtn: ".go-button",
    //     introIters: 2,
    //     correctChoice: ".glowingButton",
    //     setupChoice: "",
    //     clickableItem: "button",
    //     numIter: 4,
    // },
    {
        name: "ROAR-Morphology",
        id: "multichoice",
        startBtn: ".jspsych-fullscreen-btn",
        introBtn: ".go-button",
        introIters: 3 ,
        clickableItem: "button",
        setupChoice: "",
        correctChoice: ".glowingButton",
        numIter: 2,
    },
    // // pa has a different start button than the others (.continue i think)
    // {
    //     name: "ROAR-Phoneme",
    //     id: "pa",
    //     startBtn: ".instructionCanvasNS",
    //     setUpChoice: "",
    //     itemChoice: ".jspsych-audio-button-response-button",
    //     correctChoice: "",
    //     numIter: 2,
    // },
    // {
    //     name: "ROAR-Sentence",
    //     id: "sre",
    //     setUpChoice: "",
    //     itemChoice: ".jspsych-audio-button-response-button",
    //     correctChoice: "",
    //     numIter: 2,
    // },
    // {
    //     name: "ROAR-Word",
    //     id: "swr",
    //     setUpChoice: "",
    //     itemChoice: ".jspsych-audio-button-response-button",
    //     correctChoice: "",
    //     numIter: 2,
    // },
]

