/**
 * Arguments handed to a host-supplied {@link RecordingUploader}.
 *
 * @property path - Bucket-relative object path, generated by the SDK (see `generateFilePath`)
 * @property fileOrBlob - The bytes to upload
 * @property customMetadata - Optional metadata to attach to the stored object
 */
export interface RecordingUploadArgs {
  path: string;
  fileOrBlob: File | Blob;
  customMetadata?: Record<string, string>;
}

/**
 * The storage capability a host application supplies for recording uploads.
 *
 * The SDK owns the path convention, the upload queue, concurrency, and flush semantics; the
 * host owns only the transport. Deliberately a callback rather than a storage-client handle:
 * a closure is a plain value and crosses a module boundary safely, whereas a provider handle
 * (e.g. Firebase's `FirebaseStorage`) carries an implicit dependency on the module instance
 * that created it, so a handle created by the host and used by a separately-bundled SDK copy
 * resolves against the wrong registry. Keeping this a function is also what makes the SDK
 * provider-agnostic — see `.ai/rules/sdk-layer-architecture.md`.
 *
 * @property bucketUri - Destination bucket as a URI (e.g. `gs://my-recordings-bucket`). Used to
 *                       compose the `storagePath` persisted on the trial at enqueue time.
 * @property upload - Uploads the bytes. Resolves on success, rejects on failure.
 */
export interface RecordingUploader {
  bucketUri: string;
  upload(args: RecordingUploadArgs): Promise<void>;
}

/**
 * Input for UploadFile command.
 *
 * @property filename - The name of the file to upload
 * @property fileOrBlob - The file or blob to upload
 * @property taskId - The task ID. Used as part of the storage path.
 * @property runId - The run ID. Used as part of the storage path.
 * @property administrationId - The administration ID. Used as part of the storage path.
 * @property assessmentPid - Optional assessment PID. Used as part of the storage path. Defaults to participantId.
 * @property customMetadata - Optional custom metadata to attach to the file.
 */
export interface UploadFileInput {
  filename: string;
  fileOrBlob: File | Blob;
  taskId: string;
  runId: string;
  administrationId: string;
  assessmentPid?: string;
  customMetadata?: Record<string, string>;
}

/**
 * Input for GenerateFilePath function.
 *
 * @property filename - The name of the file to upload
 * @property taskId - The task ID. Used as part of the storage path.
 * @property participantId - The participant ID. Used as part of the storage path.
 * @property runId - The run ID. Used as part of the storage path.
 * @property administrationId - The administration ID. Used as part of the storage path.
 * @property assessmentPid - Optional assessment PID. Used as part of the storage path. Defaults to participantId.
 */
export interface GenerateFilePathInput {
  filename: string;
  taskId: string;
  participantId: string;
  runId: string;
  administrationId: string;
  assessmentPid?: string;
}

/**
 * Enum for upload statuses. Used for queue management.
 */
export const UploadStatusEnum = {
  PENDING: 'pending',
  UPLOADING: 'uploading',
  COMPLETED: 'completed',
  FAILED: 'failed',
} as const;

export type UploadStatus = (typeof UploadStatusEnum)[keyof typeof UploadStatusEnum];

/**
 * Represents the output of an upload file command.
 * @property upload - Starts the upload when called, delegating to the host's {@link RecordingUploader}.
 *                    Resolves on success, rejects on failure — the queue needs nothing else.
 * @property status - The status of the upload
 * @property filename - The name of the file to upload
 * @property storagePath - Storage URI of the file, including the bucket (e.g. `gs://bucket/path`).
 */
export type UploadFileOutput = {
  upload: () => Promise<void>;
  status: UploadStatus;
  filename: string;
  storagePath: string;
};
