export const languageOptions = {
  en: {
    gameTab: 'ROAR - Phoneme',
    url: '/game/pa',
    startText: 'In this game we are going to look for words that BEGIN with the same sound',
    breakText: 'Take a break if needed',
    breakText2: {
      break1: 'Great job',
      break2: 'Look at all those carrots',
      break3: 'You are doing great',
    },
    endText: {
      endText1: 'Take a break if needed',
      endText2: 'I have been swimming so much',
      endText3: 'You have helped me and all my friends!',
    },
    tutorialImage0: 'https://storage.googleapis.com/roar-pa/shared/map.webp',
    tutorialImage1: 'https://storage.googleapis.com/roar-pa/shared/rope.webp',
    tutorialImage2: 'https://storage.googleapis.com/roar-pa/shared/nut.webp',
    tutorialImage3: 'https://storage.googleapis.com/roar-pa/shared/wash.webp',
    tutorialImage4: 'https://storage.googleapis.com/roar-pa/shared/ball.webp',
    tutorialImage5: 'https://storage.googleapis.com/roar-pa/shared/rain.webp',
  },
  es: {
    gameTab: 'ROAR - Fonema',
    url: '/game/pa-es',
    startText: 'En este juego vamos a buscar palabras que COMIENCEN con el mismo sonido',
    breakText: 'Toma un descanso si lo necesitas',
    breakText2: {
      break1: 'Excelente trabajo',
      break2: 'Mira todas esas zanahorias',
      break3: 'Lo estás haciendo increíble',
    },
    endText: {
      // endText1: 'Toma un descanso si lo necesitas',
      // endText2: 'He estado nadando mucho',
      endText1: 'Nos has ayudado a mí y a todos(as) mis amigos(as)',
    },
    tutorialImage0: 'https://storage.googleapis.com/roar-pa/shared/hoguera.webp',
    tutorialImage1: 'https://storage.googleapis.com/roar-pa/shared/agua.webp',
    tutorialImage2: 'https://storage.googleapis.com/roar-pa/shared/invierno.webp',
    tutorialImage3: 'https://storage.googleapis.com/roar-pa/shared/cucaracha.webp',
    // tutorialImage4: 'ball.webp',
    // tutorialImage5: 'rain.webp',
  },
};
