export type {
  Transaction,
  BaseParams,
  BaseGetParams,
  BaseGetByIdParams,
  BaseGetByWhereParams,
  BaseGetAllParams,
  BaseCountParams,
  BaseCreateParams,
  BaseUpdateParams,
  BaseDeleteParams,
  BaseRunTransactionParams,
  Result,
  BaseRepository,
} from './base.repository.interface';
