import { Factory } from 'fishery';
import { faker } from '@faker-js/faker';
import type { Class, NewClass } from '../../db/schema';
import { getCoreDbClient } from '../../db/clients';
import { classes } from '../../db/schema/core';
import { ClassType } from '../../enums/class-type.enum';

/**
 * Factory for creating Class test objects.
 *
 * Usage:
 * - `ClassFactory.build()` - Creates in-memory object (unit tests)
 * - `await ClassFactory.create({ schoolId, districtId })` - Persists to database (integration tests)
 *
 * NOTE: The `orgPath` field is maintained by database triggers.
 * Do not set it manually - it will be copied from the school's path on INSERT.
 *
 * IMPORTANT: schoolId and districtId are required for database persistence.
 */
export const ClassFactory = Factory.define<Class>(({ onCreate }) => {
  onCreate(async (classObj) => {
    if (!classObj.schoolId || !classObj.districtId) {
      throw new Error('ClassFactory.create() requires schoolId and districtId');
    }

    const insertData: NewClass = {
      id: classObj.id,
      name: classObj.name,
      schoolId: classObj.schoolId,
      districtId: classObj.districtId,
      courseId: classObj.courseId,
      orgPath: 'placeholder', // Placeholder - generated by trigger
      classType: classObj.classType,
      number: classObj.number,
      period: classObj.period,
      termId: classObj.termId,
      subjects: classObj.subjects,
      location: classObj.location,
      grades: classObj.grades,
    };

    const [inserted] = await getCoreDbClient().insert(classes).values(insertData).returning();
    if (!inserted) throw new Error('Failed to insert class');
    return inserted;
  });

  return {
    id: faker.string.uuid(),
    name: `${faker.word.adjective()} ${faker.word.noun()} Class`,
    schoolId: '00000000-0000-0000-0000-000000000000', // Override required
    districtId: '00000000-0000-0000-0000-000000000000', // Override required
    courseId: null,
    orgPath: '', // Placeholder - generated by trigger
    classType: ClassType.HOMEROOM,
    number: null,
    period: null,
    termId: null,
    subjects: null,
    location: null,
    grades: null,
    schoolLevels: null,
    rosteringEnded: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
});
