import { Factory } from 'fishery';
import { faker } from '@faker-js/faker';
import type { Org, NewOrg } from '../../db/schema';
import { CoreDbClient } from '../../db/clients';
import { orgs } from '../../db/schema/core';
import type { OrgType as OrgTypeValue } from '../../enums/org-type.enum';
import { OrgType } from '../../enums/org-type.enum';

/**
 * Generates a realistic org name based on org type using location data.
 */
function generateOrgName(orgType: OrgTypeValue): string {
  const city = faker.location.city();
  const county = faker.location.county();
  const state = faker.location.state();

  switch (orgType) {
    case OrgType.NATIONAL:
      return `${faker.location.country()} Department of Education`;
    case OrgType.STATE:
      return `${state} Department of Education`;
    case OrgType.LOCAL:
      return `${county} Education Authority`;
    case OrgType.DISTRICT:
      return `${city} School District`;
    case OrgType.SCHOOL:
      return `${city} ${faker.helpers.arrayElement(['Elementary', 'Middle', 'High'])} School`;
    case OrgType.DEPARTMENT:
      return `${faker.helpers.arrayElement(['Mathematics', 'Science', 'English', 'History', 'Arts'])} Department`;
    default:
      return faker.company.name();
  }
}

/**
 * Factory for creating Org test objects.
 *
 * Usage:
 * - `OrgFactory.build()` - Creates in-memory object (unit tests)
 * - `await OrgFactory.create()` - Persists to database (integration tests)
 * - `await OrgFactory.create({ parentOrgId: districtId })` - Create child org
 *
 * Note: The `path` field is maintained by database triggers.
 * Do NOT set it manually - it will be generated on INSERT based on parentOrgId.
 */
export const OrgFactory = Factory.define<Org>(({ onCreate, params }) => {
  onCreate(async (org) => {
    // Root orgs must have isRosteringRootOrg = true due to DB constraint
    const isRoot = !org.parentOrgId;
    const isRosteringRootOrg = isRoot ? true : org.isRosteringRootOrg;

    const insertData: NewOrg = {
      id: org.id,
      name: org.name,
      abbreviation: org.abbreviation,
      orgType: org.orgType,
      parentOrgId: org.parentOrgId,
      path: 'placeholder', // Placeholder - generated by trigger
      locationAddressLine1: org.locationAddressLine1,
      locationAddressLine2: org.locationAddressLine2,
      locationCity: org.locationCity,
      locationStateProvince: org.locationStateProvince,
      locationPostalCode: org.locationPostalCode,
      locationCountry: org.locationCountry,
      ncesId: org.ncesId,
      mdrNumber: org.mdrNumber,
      stateId: org.stateId,
      schoolNumber: org.schoolNumber,
      isRosteringRootOrg,
      rosteringEnded: org.rosteringEnded,
    };

    const [inserted] = await CoreDbClient.insert(orgs).values(insertData).returning();
    if (!inserted) throw new Error('Failed to insert org');
    return inserted;
  });

  // Use overridden orgType if provided, otherwise default to district
  const orgType = params.orgType ?? OrgType.DISTRICT;
  const name = params.name ?? generateOrgName(orgType);
  // Take the first character of each space-split word, then strip any non-alphanumeric
  // characters. faker.location.city() returns real-world names like "Town 'n' Country"
  // or "St. Louis" whose first-char-per-word would otherwise produce abbreviations
  // (e.g. "T'CHS") that violate the `orgs_abbreviation_format` check constraint
  // (`^[A-Za-z0-9]+$`). Falls back to 'ORG' when sanitization leaves an empty string,
  // since the constraint also rejects empty abbreviations.
  const abbreviation =
    name
      .split(' ')
      .map((word) => word.charAt(0))
      .join('')
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '') || 'ORG';

  return {
    id: faker.string.uuid(),
    name,
    abbreviation,
    orgType,
    parentOrgId: null,
    path: '', // Placeholder - generated by trigger
    locationAddressLine1: null,
    locationAddressLine2: null,
    locationCity: null,
    locationStateProvince: null,
    locationPostalCode: null,
    locationCountry: null,
    locationLatLong: null,
    ncesId: null,
    mdrNumber: null,
    stateId: null,
    schoolNumber: null,
    isRosteringRootOrg: false,
    rosteringEnded: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
});
