name: Version and Publish

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Type of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version_and_publish:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump_package_version.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_BOT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install and Package 🔧
        run: |
          npm ci
          npm run package

      - name: Bump package version
        id: bump_package_version
        run: |
          npm version ${{ github.event.inputs.version-type }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            const issue = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Combined workflow failed",
              body: `The workflow failed on [${context.sha.substring(0, 7)}](${context.payload.repository.html_url}/commit/${context.sha}). Please check it.`,
            };
            github.rest.issues.create(issue);

  deploy_to_production:
    needs: version_and_publish
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and build
        run: npm ci && npm run build:prod

      - name: Deploy production app
        uses: ./.github/actions/deploy
        id: deployment
        with:
          firebase-channel: default
          firebase-project-id: ${{ secrets.FIREBASE_PROJECT_ID_ASSESSMENT }}
          gcp-workload-identity-provider: ${{ secrets.FIREBASE_WORKLOAD_IDENTITY_PROVIDER_ASSESSMENT }}
          gcp-service-account-id: ${{ secrets.FIREBASE_APP_SERVICE_ACCOUNT_ID_ASSESSMENT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: production

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            const issue = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Combined workflow failed",
              body: `The workflow failed on [${context.sha.substring(0, 7)}](${context.payload.repository.html_url}/commit/${context.sha}). Please check it.`,
            };
            github.rest.issues.create(issue);
