export const VALIDATION = {
  RESPONSE_TIME_LOW_THRESHOLD: 250,
  ACCURACY_THRESHOLD: 0.1,
};

export const RVP = {
  DURATION_MARK_FIX_PRACTICE_AV: 2000,
  DURATION_STIM_PRACTICE_AV: 2000,

  DURATION_MARK_FIX_PRACTICE: 1000,
  DURATION_STIM_PRACTICE: 700,

  DURATION_RESP_DEMO_MAX: 90_000,
  DURATION_RESP_PRACTICE_AV_MAX: 30_000,
  DURATION_RESP_PRACTICE_MAX: 20_000,
  DURATION_RESP_TEST_MAX: 11_000,
};
