<template>
  <div v-if="!refData">
    <SkeletonTable />
  </div>
  <div v-else>
    <div v-if="allowExport" class="flex flex-row w-full gap-2 py-2" style="justify-content: flex-end;">
      <Button label="Export Selected" :disabled="refSelectedRows.length === 0" @click="exportCSV" />
      <Button label="Export Whole Table" @click="exportFullCSV" />
    </div>
    <DataTable 
      :value="refData" 
      :rowHover="true" 
      :reorderableColumns="true" 
      :resizableColumns="true"
      v-model:selection="refSelectedRows"
      removableSort
      sortMode="multiple"
      showGridlines
      v-model:filters="refFilters"
      filterDisplay="menu"
    >
      <Column 
        selectionMode="multiple" 
        headerStyle="width: 3rem"
      ></Column>
      <Column 
        v-for="col of columns" 
        :key="col.field" 
        :header="col.header" 
        :field="col.field"
        :dataType="col.dataType"
        :sortable="(col.sort !== false)"
        :showFilterMatchModes="!col.useMultiSelect"
      >
        <template v-if="col.dataType === 'date'" #body="{ data }">
          {{ getFormattedDate(data[col.field]) }}
        </template>
        <template v-if="col.dataType" #filter="{ filterModel }">
          <InputText 
            v-if="col.dataType === 'text' && !col.useMultiSelect"
            type="text" v-model="filterModel.value" 
            class="p-column-filter" 
            placeholder="Search" 
          />
          <MultiSelect 
            v-if="col.useMultiSelect"
            v-model="filterModel.value" 
            :options="refOptions[col.field]" 
            placeholder="Any"
            :showToggleAll="false" 
            class="p-column-filter" 
          />
          <Calendar 
            v-if="col.dataType === 'date' && !col.useMultiSelect"
            v-model="filterModel.value" 
            dateFormat="mm/dd/yy" 
            placeholder="mm/dd/yyyy" 
          />
        </template>
      </Column>
    </DataTable>
  </div>
</template>
<script setup>
import { ref } from 'vue';
import { FilterMatchMode, FilterOperator } from "primevue/api";
import SkeletonTable from "@/components/SkeletonTable.vue"
import _get from 'lodash/get'
import _map from 'lodash/map'
import _forEach from 'lodash/forEach'
import _find from 'lodash/find'
import _filter from 'lodash/filter'
import _toUpper from 'lodash/toUpper'
import _startCase from 'lodash/startCase'
import _flatMap from 'lodash/flatMap'
import Papa from "papaparse";

/*
Using the DataTable
Required Props: columns, data
Optional Props: allowExport (default: true)

Columns:
Array of objects consisting of a field and header at minimum.
- Field must match the key of the entry in the data object.
- Header is an optional string that is displayed at the top of 
      the column.
- dataType is a string that defines the data type of the column.
      options are TEXT, NUMERIC, or DATE
- Sort (optional) is a boolean field that determines whether sorting
      is to be allowed on the field. If it is not present, defaults to true.
- allowMultipleFilters (optional) is a boolean field that determines whether
      users have the option of apply multiple filters.
- useMultiSelect is an optional boolean field that determines whether the
      filter will be a multi-select dropdown. options are generated by the 
      given data.
*/

const props = defineProps({
  columns: {type:Array, required: true},
  data: {type: Array, required: true},
  allowExport: {type: Boolean, default: true}
});

let selectedRows = [];
const refSelectedRows = ref(selectedRows);

const exportCSV = async () => {
  const csv = Papa.unparse(_flatMap(refSelectedRows.value));
  const blob = new Blob([csv]);
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob, { type: 'text/plain' });
  a.download = 'runs.csv';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
};

const exportFullCSV = async () => {
  const csv = Papa.unparse(_flatMap(refData.value))
  const blob = new Blob([csv]);
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob, { type: 'text/plain' });
  a.download = 'runs.csv';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
};

// Generate filters and options objects
const valid_dataTypes = ['NUMERIC', 'TEXT', 'DATE'];
let filters = {};
let options = {};
_forEach(props.columns, column => {
  // Check if header text is supplied; if not, generate.
  if(!_get(column, 'header')){
    column['header'] = _startCase(_get(column, 'field'))
  }
  const dataType = _toUpper(_get(column, 'dataType'));
  let returnMatchMode = null;
  if(valid_dataTypes.includes(dataType)){
    if(dataType === 'NUMERIC'){
      returnMatchMode = { value: null, matchMode: FilterMatchMode.EQUALS};
    } else if(dataType === 'TEXT'){
      returnMatchMode = { value: null, matchMode: FilterMatchMode.STARTS_WITH};
    } else if(dataType === 'DATE'){
      returnMatchMode = { value: null, matchMode: FilterMatchMode.DATE_IS};
    }
    
    if(_get(column, 'useMultiSelect')){
      returnMatchMode = { value: null, matchMode: FilterMatchMode.IN};
      options[column.field] = getUniqueOptions(column);
    }
  }
  if(_get(column, 'allowMultipleFilters') === true && returnMatchMode){
    filters[column.field] = {
      operator: FilterOperator.AND,
      constraints: [returnMatchMode]
    }
  } else if(returnMatchMode) {
    filters[column.field] = returnMatchMode;
  }
})
const refOptions = ref(options);
const refFilters = ref(filters);

// Grab list of fields defined as dates
let dateFields = _filter(props.columns, col => _toUpper(col.dataType) === 'DATE');
dateFields = _map(dateFields, col => col.field);

let computedData = _forEach(props.data, entry => {
  // Clean up date fields to use Date objects
  _forEach(dateFields, field => {
    let dateEntry = _get(entry, field);
    if(dateEntry !== null) entry[field] = new Date(dateEntry);
  })
})
const refData = ref(computedData);

// Generate list of options given a column
function getUniqueOptions(column){
  const field = _get(column, 'field');
  let options = [];
  _forEach(props.data, entry => {
    if(!options.includes(entry[field])){
      options.push(entry[field]);
    }
  });
  return options
}

function getFormattedDate(date){
  if(date){
    return date.toLocaleDateString('en-us', { weekday: 'long', year: 'numeric', month: 'short', day: 'numeric' })
  } else return ''
}
</script>