<template>
  <div v-if="!computedData">
    <SkeletonTable />
  </div>
  <div v-else>
    <div v-if="allowExport" class="flex flex-row w-full gap-2 py-2" style="justify-content: flex-end;">
      <Button label="Export Selected" :disabled="refSelectedRows.length === 0" @click="exportCSV(true, $event)" />
      <Button label="Export Whole Table" @click="exportCSV(false, $event)" />
    </div>
    <DataTable ref="dataTable" :value="computedData" :rowHover="true" :reorderableColumns="true" :resizableColumns="true"
      :exportFilename="exportFilename" v-model:selection="refSelectedRows" removableSort sortMode="multiple" showGridlines
      v-model:filters="refFilters" filterDisplay="menu" paginator :rows="props.pageLimit" :alwaysShowPaginator="true"
      :totalRecords="totalRecords" lazy :loading="props.loading" scrollable @page="handlePageEvent($event)">
      <Column selectionMode="multiple" headerStyle="width: 3rem" frozen></Column>
      <Column v-for="col of columns" :key="col.field" :header="col.header" :field="col.field" :dataType="col.dataType"
        :sortable="(col.sort !== false)" :showFilterMatchModes="!col.useMultiSelect"
        :showFilterOperator="col.allowMultipleFilters === true" :showAddButton="col.allowMultipleFilters === true"
        :frozen="col.pinned">
        <template #body="{ data }">
          <div v-if="col.tag && _get(data, col.field) !== undefined">
            <Tag :severity="_get(data, col.severityField)" :value="_get(data, col.field)"
              :icon="_get(data, col.iconField)" :style="`background-color: ${_get(data, col.tagColor)}; min-width: 2rem;`"
              rounded />
          </div>
          <div v-else-if="col.emptyTag">
            <div class="circle" :style="`background-color: ${_get(data, col.tagColor)};`" />
          </div>
          <div v-else-if="col.dataType === 'date'">
            {{ getFormattedDate(_get(data, col.field)) }}
          </div>
          <div v-else>
            {{ _get(data, col.field) }}
          </div>
        </template>
        <template v-if="col.dataType" #filter="{ filterModel }">
          <InputText v-if="col.dataType === 'text' && !col.useMultiSelect" type="text" v-model="filterModel.value"
            class="p-column-filter" placeholder="Search" />
          <MultiSelect v-if="col.useMultiSelect" v-model="filterModel.value" :options="_get(refOptions, col.field)"
            placeholder="Any" :showToggleAll="false" class="p-column-filter" />
          <Calendar v-if="col.dataType === 'date' && !col.useMultiSelect" v-model="filterModel.value"
            dateFormat="mm/dd/yy" placeholder="mm/dd/yyyy" />
          <div v-if="col.dataType === 'boolean' && !col.useMultiSelect" class="flex flex-row gap-2">
            <TriStateCheckbox inputId="booleanFilter" v-model="filterModel.value" style="padding-top: 2px;" />
            <label for="booleanFilter">{{ col.header + '?' }}</label>
          </div>
        </template>
      </Column>
      <template #empty>
        No data!
      </template>
    </DataTable>
  </div>
</template>
<script setup>
import { ref, onMounted, computed } from 'vue';
import { FilterMatchMode, FilterOperator } from "primevue/api";
import SkeletonTable from "@/components/SkeletonTable.vue"
import _get from 'lodash/get'
import _set from 'lodash/set'
import _map from 'lodash/map'
import _forEach from 'lodash/forEach'
import _find from 'lodash/find'
import _filter from 'lodash/filter'
import _toUpper from 'lodash/toUpper'
import _startCase from 'lodash/startCase'
import _flatMap from 'lodash/flatMap'

/*
Using the DataTable
Required Props: columns, data
Optional Props: allowExport (default: true), exportFilename (default: 'datatable-export')

Columns:
Array of objects consisting of a field and header at minimum.
- Field must match the key of the entry in the data object.
- Header is an optional string that is displayed at the top of 
      the column.
- dataType is a string that defines the data type of the column.
      options are TEXT, NUMERIC, or DATE
- Sort (optional) is a boolean field that determines whether sorting
      is to be allowed on the field. If it is not present, defaults to true.
- allowMultipleFilters (optional) is a boolean field that determines whether
      users have the option of apply multiple filters.
- useMultiSelect is an optional boolean field that determines whether the
      filter will be a multi-select dropdown. options are generated by the 
      given data.
- Pinned (optional) is a boolean field allowing the column to persist when 
      scrolled left-to-right. It is suggested that this only be used on
      the leftmost column. 
*/

const props = defineProps({
  columns: { type: Array, required: true },
  data: { type: Array, required: true },
  allowExport: { type: Boolean, default: true },
  exportFilename: { type: String, default: 'datatable-export' },
  pageLimit: { type: Number, default: 15 },
  totalRecords: { type: Number, required: false },
  loading: { type: Boolean, default: false },
});

const totalRecords = ref();
onMounted(() => {
  totalRecords.value = props.totalRecords ?? props.data.length;
})

let selectedRows = [];
const refSelectedRows = ref(selectedRows);

const dataTable = ref();

const exportCSV = (exportSelected) => {
  dataTable.value.exportCSV({ selectionOnly: exportSelected });
};

// Generate filters and options objects
const valid_dataTypes = ['NUMERIC', 'NUMBER', 'TEXT', 'STRING', 'DATE', 'BOOLEAN'];
let filters = {};
let options = {};
_forEach(props.columns, column => {
  // Check if header text is supplied; if not, generate.
  if (!_get(column, 'header')) {
    column['header'] = _startCase(_get(column, 'field'))
  }
  const dataType = _toUpper(_get(column, 'dataType'));
  let returnMatchMode = null;
  if (valid_dataTypes.includes(dataType)) {
    if (dataType === 'NUMERIC' || dataType === 'NUMBER' || dataType === 'BOOLEAN') {
      returnMatchMode = { value: null, matchMode: FilterMatchMode.EQUALS };
    } else if (dataType === 'TEXT' || dataType === 'STRING') {
      returnMatchMode = { value: null, matchMode: FilterMatchMode.STARTS_WITH };
    } else if (dataType === 'DATE') {
      returnMatchMode = { value: null, matchMode: FilterMatchMode.DATE_IS };
    }

    if (_get(column, 'useMultiSelect')) {
      returnMatchMode = { value: null, matchMode: FilterMatchMode.IN };
      options[column.field] = getUniqueOptions(column);
    }
  }
  if (returnMatchMode) {
    filters[column.field] = {
      operator: FilterOperator.AND,
      constraints: [returnMatchMode]
    }
  }
})
const refOptions = ref(options);
const refFilters = ref(filters);

// Grab list of fields defined as dates
let dateFields = _filter(props.columns, col => _toUpper(col.dataType) === 'DATE');
dateFields = _map(dateFields, col => col.field);

const computedData = computed(() => {
  const data = JSON.parse(JSON.stringify(props.data));
  _forEach(data, (entry) => {
    // Clean up date fields to use Date objects
    _forEach(dateFields, field => {
      let dateEntry = _get(entry, field);
      if (dateEntry !== null) {
        const dateObj = new Date(dateEntry);
        _set(entry, field, dateObj);
      }
    })
  });
  return data;
});

// Generate list of options given a column
function getUniqueOptions(column) {
  const field = _get(column, 'field');
  let options = [];
  _forEach(props.data, entry => {
    if (!options.includes(_get(entry, field))) {
      options.push(_get(entry, field));
    }
  });
  return options
}

function getFormattedDate(date) {
  if (date && !isNaN(date)) {
    return date.toLocaleDateString('en-us', { weekday: 'long', year: 'numeric', month: 'short', day: 'numeric' })
  } else return ''
}

const emit = defineEmits(['page']);
const handlePageEvent = (event) => {
  emit('page', event)
}
</script>
<style>
.circle {
  border-color: white;
  display: inline-block;
  border-radius: 50%;
  border-width: 5px;
  height: 25px;
  width: 25px;
  vertical-align: middle;
  margin-right: 10px;
}
</style>