export enum SdkErrorCode {
  START_RUN_FAILED = 'START_RUN_FAILED',
  ABORT_RUN_FAILED = 'ABORT_RUN_FAILED',
  FINISH_RUN_FAILED = 'FINISH_RUN_FAILED',
  WRITE_TRIAL_FAILED = 'WRITE_TRIAL_FAILED',
  UPDATE_ENGAGEMENT_FLAGS_FAILED = 'UPDATE_ENGAGEMENT_FLAGS_FAILED',
  GET_VARIANT_ID_FAILED = 'GET_VARIANT_ID_FAILED',
}
