export const VALIDATION = {
  RESPONSE_TIME_LOW_THRESHOLD: 250,
  ACCURACY_THRESHOLD: 0.1,
};

// TODO: copied from RVP - check that make sense
export const CR = {
  DURATION_MARK_FIX_PRACTICE_AV: 2000,
  DURATION_STIM_PRACTICE_AV: 2000,

  DURATION_MARK_FIX_PRACTICE: 1000,
  DURATION_STIM_PRACTICE: 250,

  DURATION_RESP_DEMO_MAX: 90_000,
  DURATION_RESP_PRACTICE_AV_MAX: 30_000,
  DURATION_RESP_PRACTICE_MAX: 20_000,
  DURATION_RESP_TEST_MAX: 11_000,
  DURATION_RESP_WARN_TIMEOUT: 3_000,

  VD_CM: 50,
  WIDTH_SCREEN_PX: 30,
  ECCENT_TARG_DEG: 6,

  RATIO_MAX_100: 1,
  RATIO_MAX_075: 0.75,
  RATIO_MAX_050: 0.5,
  DIST_FLANK_MIN: 1.1, // in % of stimuli size

  VD_CM_MIN: 20,
  VD_CM_MAX: 100,

  // TODO: make sure they are coming from config
  // TODO: add fallbacks for CR trial
  // DURATION_TARG_PRE
};
