name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write
  id-token: write

jobs:
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Lint & Format
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-node-environment

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Type check
        run: npm run check-types

  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Test
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CORE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/roar_core_test
      ASSESSMENT_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/roar_assessment_test
      FGA_API_URL: http://localhost:8080

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_GITHUB_PAT }}

      - name: Install OpenFGA
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: openfga/openfga
          tag: v1.12.1
          cache: enable

      - name: Start OpenFGA
        run: openfga run &

      - name: Setup environment
        uses: ./.github/actions/setup-node-environment

      - name: Create test databases
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE roar_core_test;"
          PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE roar_assessment_test;"

      - name: Run OpenFGA model tests
        uses: openfga/action-openfga-test@v0.1.2
        with:
          test_path: packages/authz/tests

      - name: Run all tests
        run: npm run test
        env:
          RUN_INTEGRATION_TESTS: "true"
          DOTENV_PRIVATE_KEY_TEST: ${{ secrets.DOTENV_PRIVATE_KEY_TEST }}

      - name: Report dashboard coverage
        if: success()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: "apps/dashboard"
          name: Dashboard

      - name: Report backend coverage
        if: success()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: "apps/backend"
          name: Backend

  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Build the application
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DOTENV_PRIVATE_KEY_DEVELOPMENT: ${{ secrets.DOTENV_PRIVATE_KEY_DEVELOPMENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_GITHUB_PAT }}

      - name: Setup environment
        uses: ./.github/actions/setup-node-environment

      - name: Build application
        run: npm run build

  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # End-to-end tests
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge]
        containers: [1, 2, 3, 4]
    container:
      image: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
      options: --user 1001
    env:
      DOTENV_PRIVATE_KEY_DEVELOPMENT: ${{ secrets.DOTENV_PRIVATE_KEY_DEVELOPMENT }}
      DOTENV_PRIVATE_KEY_TEST: ${{ secrets.DOTENV_PRIVATE_KEY_TEST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_GITHUB_PAT }}

      - name: Setup environment
        uses: ./.github/actions/setup-node-environment

      - name: Build
        run: npm run build

      - name: Execute Cypress tests
        uses: cypress-io/github-action@v6
        env:
          # Run tests against development environment to catch regressions before deployment
          CYPRESS_BASE_URL: "http://127.0.0.1:4173"
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: "${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install: false
          start: npm run preview -- --host
          tag: ${{ github.event_name }},e2e,${{ matrix.browser }}
          wait-on: ${{ env.CYPRESS_BASE_URL }}
          wait-on-timeout: 120
          record: true
          parallel: true
          browser: ${{ matrix.browser }}
          ci-build-id: ${{ github.run_id }}-e2e-${{ matrix.browser }}
          working-directory: apps/dashboard
          spec: |
            cypress/e2e/parent/default-tests/**/*.cy.js
            cypress/e2e/participant/default-tests/**/*.cy.js
            cypress/e2e/partner-admin/default-tests/**/*.cy.js

  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Component Tests
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  component-tests:
    name: Component tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge]
    container:
      image: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
      options: --user 1001
    env:
      DOTENV_PRIVATE_KEY_DEVELOPMENT: ${{ secrets.DOTENV_PRIVATE_KEY_DEVELOPMENT }}
      DOTENV_PRIVATE_KEY_TEST: ${{ secrets.DOTENV_PRIVATE_KEY_TEST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_GITHUB_PAT }}

      - name: Setup environment
        uses: ./.github/actions/setup-node-environment

      - name: Build
        run: npm run build

      - name: Execute Cypress tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: "http://127.0.0.1:4173"
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: "${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          component: true
          install: false
          start: npm run preview -- --host
          tag: ${{ github.event_name }},component,${{ matrix.browser }}
          wait-on: ${{ env.CYPRESS_BASE_URL }}
          wait-on-timeout: 120
          record: true
          parallel: true
          browser: ${{ matrix.browser }}
          ci-build-id: ${{ github.run_id }}-component-${{ matrix.browser }}
          working-directory: apps/dashboard
          spec: |
            src/**/*.cy.js

  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Deploy to Preview Environment
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    timeout-minutes: 10
    env:
      DOTENV_PRIVATE_KEY_STAGING: ${{ secrets.DOTENV_PRIVATE_KEY_STAGING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build preview app
        uses: ./.github/actions/build
        with:
          environment: staging
          github-pat: ${{ secrets.CI_GITHUB_PAT }}

      - name: Deploy preview app
        uses: ./.github/actions/deploy-firebase-hosting
        id: deployment
        with:
          firebase-channel: preview
          firebase-project-id: ${{ secrets.CI_FIREBASE_PROJECT_ID_ADMIN_STAGING }}
          gcp-workload-identity-provider: ${{ secrets.CI_FIREBASE_WORKLOAD_IDENTITY_PROVIDER_ADMIN_STAGING }}
          gcp-service-account-id: ${{ secrets.CI_FIREBASE_HOSTING_SERVICE_ACCOUNT_ID_ADMIN_STAGING }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dist-path: build/apps/dashboard/dist
          firebase-config-path: build/apps/dashboard/firebase/admin/firebase.json

      # - name: Whitelist AppCheck admin environment
      #   if: ${{ success() }}
      #   uses: ./.github/actions/whitelist-appcheck-environment
      #   with:
      #     project-id: ${{ secrets.CI_FIREBASE_PROJECT_ID_ADMIN_STAGING }}
      #     service-account-key: ${{ secrets.CI_FIREBASE_SERVICE_ACCOUNT_ADMIN_STAGING }}
      #     appcheck-site-key: ${{ secrets.FIREBASE_APPCHECK_SITE_KEY_ADMIN_STAGING }}
      #     environment-url: ${{ fromJson(steps.firebase-deploy-preview.outputs.urls)[0] }}

      # - name: Whitelist AppCheck assessment environment
      #   if: ${{ success() }}
      #   uses: ./.github/actions/whitelist-appcheck-environment
      #   with:
      #     project-id: ${{ secrets.FIREBASE_PROJECT_ID_ASSESSMENT_STAGING }}
      #     service-account-key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASSESSMENT_STAGING }}
      #     appcheck-site-key: ${{ secrets.FIREBASE_APPCHECK_SITE_KEY_ASSESSMENT_STAGING }}
      #     environment-url: ${{ fromJson(steps.firebase-deploy-preview.outputs.urls)[0] }}

  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Detect changed assessments
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  detect-assessment-changes:
    name: Detect changed assessments
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Detect changes
        id: detect
        uses: ./.github/actions/detect-assessment-changes

  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Assessment E2E tests
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  e2e-assessments:
    name: E2E ${{ matrix.assessment }} (${{ matrix.browser }})
    needs: [detect-assessment-changes]
    if: needs.detect-assessment-changes.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        assessment: ${{ fromJson(needs.detect-assessment-changes.outputs.matrix) }}
        browser: [chrome, edge]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-node-environment

      - name: Build workspace packages
        run: npx turbo run build --filter='./packages/*'

      - name: Start researcher infrastructure
        run: docker compose -f docker-compose.researcher.yml up -d --wait
        timeout-minutes: 10

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm run dev:ci
          browser: ${{ matrix.browser }}
          working-directory: apps/assessments/${{ matrix.assessment }}
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120
          record: true
          parallel: true
          tag: ${{ github.event_name }},${{ matrix.assessment }},${{ matrix.browser }}
          spec: cypress/e2e/**/*
          ci-build-id: ${{ github.run_id }}-${{ matrix.assessment }}-${{ matrix.browser }}
        env:
          FIREBASE_AUTH_EMULATOR_HOST: 127.0.0.1:9099
          BACKEND_URL: http://localhost:4000
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          COMMIT_INFO_MESSAGE: "${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
