name: Run Cypress Participant Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      pr_branch:
        description: 'Checkout this branch from the PR and execute CI/CD tests on it.'
        required: true

concurrency:
  group: ci-preview-tests-${{ github.ref }}-3
  cancel-in-progress: true

jobs:
  cypress-run:
    name: Run Cypress Participant Tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, edge]
        containers: [1, 2]
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
      NODE_ENV: 'test'
      CLEVER_USERNAME: ${{ secrets.CLEVER_USERNAME }}
      CLEVER_PASSWORD: ${{ secrets.CLEVER_PASSWORD }}
      CYPRESS_BASE_URL: 'http://localhost:5173'
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      COMMIT_INFO_MESSAGE: Tests for PR ${{ github.event.number }} "${{ github.event.pull_request.title }}" from commit "${{ github.event.pull_request.head.sha }}"
      COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
      PARTNER_ADMIN_USERNAME: ${{ secrets.PARTNER_ADMIN_USERNAME }}
      PARTNER_ADMIN_PASSWORD: ${{ secrets.PARTNER_ADMIN_PASSWORD }}
      PARTNER_ADMIN_ID: ${{ secrets.PARTNER_ADMIN_ID }}
      PARTICIPANT_USERNAME: ${{ secrets.PARTICIPANT_USERNAME}}
      PARTICIPANT_PASSWORD: ${{ secrets.PARTICIPANT_PASSWORD }}
      PARTICIPANT_EMAIL: ${{ secrets.PARTICIPANT_EMAIL }}
      PARTICIPANT_EMAIL_PASSWORD: ${{ secrets.PARTICIPANT_EMAIL_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Use the branch from the PR if workflow is triggered manually, otherwise use the PR branch from the event
          ref: ${{ github.event.inputs.pr_branch || github.event.pull_request.head.ref }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          build: npm ci && npm run build
          start: npm run dev
          wait-on: ${{ env.CYPRESS_BASE_URL }}
          wait-on-timeout: 120
          record: true
          parallel: true
          spec: 'cypress/e2e/participant/default-tests/**/*'
          ci-build-id: ${{ github.run_id }}-${{ matrix.browser }}
