name: Cypress Tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        browser: [chrome, firefox, edge, safari]
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
          record: true
          parallel: true # Runs test in parallel using settings above
          browser: ${{ matrix.browser }}
          spec: cypress/e2e/participant/checkLegalDoc.cy.js # Runs tests in this folder
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}