name: Deploy to Staging

# on:
#   push:
#     branches:
#       - main
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}

jobs:
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Prepare deployment
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  prepare-deployment:
    name: Prepare deployment
    runs-on: ubuntu-latest
    outputs:
      target-envs: ${{ steps.environment-configs.outputs.envs }}
    steps:
      - name: Generate environment matrix
        id: environment-configs
        run: |
          defaultEnvironment='{"name":"staging","projectId":"${{ secrets.FIREBASE_PROJECT_ID_ADMIN_STAGING }}","envFileKeyRef":"DOTENV_PRIVATE_KEY_STAGING","firebaseServiceAccountRef":"FIREBASE_SERVICE_ACCOUNT_ADMIN_STAGING"}'
          additionalEnvironments='${{ vars.STAGING_ENVIRONMENTS }}'
          envs="[$(echo "$defaultEnvironment" | jq -c '.')]"
          if [ -n "$additionalEnvironments" ]; then
            envs="$envs, $additionalEnvironments"
          fi
          echo "envs=$(jq -cn --argjson environments "$envs" '{environments: $environments}')" >> $GITHUB_OUTPUT

  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  # Build and deploy the application
  # ––––––––––––––––––––––––––––––––––––––––––––––– #
  build-and-deploy:
    needs: [prepare-deployment]
    name: Deploy to ${{ fromJson(needs.prepare-deployment.outputs.target-envs).environments[matrix.index].name }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare-deployment.outputs.target-envs).environments }}

    steps:
      - name: Retrieve environment configuration
        id: config
        run: |
          config='${{ toJson(fromJson(needs.prepare-deployment.outputs.target-envs).environments[matrix.index]) }}'
          echo "JSON_RESPONSE<<EOF" >> "$GITHUB_OUTPUT"
          echo "$config" | jq -c '.' >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Use configuration
        run: |
          projectId=$(echo '${{ steps.config.outputs.JSON_RESPONSE }}' | jq -r .projectId)
          envFileKeyRef=$(echo '${{ steps.config.outputs.JSON_RESPONSE }}' | jq -r .envFileKeyRef)
          firebaseServiceAccountRef=$(echo '${{ steps.config.outputs.JSON_RESPONSE }}' | jq -r .firebaseServiceAccountRef)
          echo "Project ID: $projectId"
          echo "Env File Key Ref: $envFileKeyRef"
          echo "Firebase Service Account Ref: $firebaseServiceAccountRef"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CI_GITHUB_PAT }}

      - name: Setup environment
        uses: ./.github/actions/setup-node-environment

      - name: Build application
        run: npm run build

      # - name: Debug
      #   run: |
      #     echo "Matrix: ${{ toJson(matrix) }}"

      # - name: Deploy to Firebase Hosting Channel
      #   id: firebase-deploy-staging
      #   uses: FirebaseExtended/action-hosting-deploy@v0.9.0
      #   with:
      #     repoToken: ${{ secrets.GITHUB_TOKEN }}
      #     firebaseServiceAccount: ${{ secrets[matrix.firebaseServiceAccountRef] }}
      #     projectId: ${{ matrix.projectId }}

      # - name: Update deployment status
      #   if: ${{ success() }}
      #   run: echo "url=${{ fromJson(steps.firebase-deploy-staging.outputs.urls)[0] }}" >> $GITHUB_OUTPUT
